#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Values.rbac.create -}}
{{- $root := . -}}
{{- range append .Values.watchNamespaces .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if $root.Values.watchAnyNamespace }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  {{- if $root.Values.watchAnyNamespace }}
  name: strimzi-cluster-operator-namespaced
  {{- else }}
  name: strimzi-cluster-operator
  {{- end }}
  namespace: {{ . }}
  labels:
    app: {{ template "strimzi.name" $root }}
    chart: {{ template "strimzi.chart" $root }}
    component: role-binding
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ $root.Values.serviceAccount }}
    namespace: {{ $root.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: strimzi-cluster-operator-namespaced
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
