#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to Azure Kubernetes Service

env:
  AZURE_CONTAINER_REGISTRY: Degree # set this to the name of your container registry
  PROJECT_NAME: Degree-workflow              # set this to your project's name
  RESOURCE_GROUP: degree-test-group          # set this to the resource group containing your AKS cluster
  CLUSTER_NAME: degree_v1              # set this to the name of your AKS cluster
  REGISTRY_URL: degree.azurecr.io # set this to the URL of your registry

on: [workflow_dispatch]

permissions:
    id-token: write
    contents: read
    pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kubctl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0' # default is latest stable
        id: install

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure Container Registry Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_URL }}
          username: ${{env.AZURE_CONTAINER_REGISTRY}}
          password: secrets.ACR_PASSWORD

      - name: Set up AKS context (if using AKS)
        uses: azure/k8s-set-context@v1
        with:
          method: service-principal
          cluster-type: 'arc'
          cluster-name: ${{env.CLUSTER_NAME}}
          resource-group: ${{env.RESOURCE_GROUP}}
        id: setcontext

      - name: Current config
        run: kubectl config view

      - name: Install Helm Chart from ACR
        run: helm install benchmark oci://${{env.AZURE_CONTAINER_REGISTRY}}.azurecr.io/helm/openmessaging-benchmark --version 1.0.0

      - name: Kubectl get all resources
        run: kubectl get all

# This is where copy file from pod starts

#      - name: Copy File from Pod
#        run: |
#          kubectl cp <namespace>/<pod-name>:/path/to/remote/file /path/to/runner/file
#
#      - name: Upload File to Artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: my-file
#          path: /path/to/runner/file
